author: [Zhuowei,MinecraftDawn,lasteamlab]
description: Implementation of the Minecraft PI modding API
main: io.github.lasteamlab.raspberryjuice2.RaspberryJuice2
name: RaspberryJuice2
startup: postworld
version: '1.15-0.0'
api-version: 1.13